AWSTemplateFormatVersion: '2010-09-09'
Description: Template para crear la tabla DynamoDB para lanzamientos espaciales

Resources:
  SpaceXLaunchesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SpaceXLaunches
      AttributeDefinitions:
        - AttributeName: launch_id
          AttributeType: S
        - AttributeName: launch_date
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: launch_id
          KeyType: HASH
        - AttributeName: launch_date
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
